import { useState, useEffect, useCallback } from "react";
import { useParams, useNavigate, useLocation } from "react-router-dom";
import { ArrowLeft, Save, Building2, Globe, Monitor, Zap, Minus, Plus, Trash2, Package, Camera, ImageOff, X, CreditCard } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Input } from "@/components/ui/Input";
import { Select } from "@/components/ui/Select";
import { Textarea } from "@/components/ui/Textarea";
import { Alert, AlertTitle, AlertDescription } from "@/components/ui/Alert";
import { Spinner } from "@/components/ui/Spinner";
import { businessAPI, searchAPI, adminAPI, paymentAPI } from "@/lib/api";
import ImageManager from "@/components/ImageManager";
import useAuthStore from "@/store/useAuthStore";

const DAYS = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
];
const DAY_LABELS = {
  monday: "Monday",
  tuesday: "Tuesday",
  wednesday: "Wednesday",
  thursday: "Thursday",
  friday: "Friday",
  saturday: "Saturday",
  sunday: "Sunday",
};

const defaultHours = Object.fromEntries(
  DAYS.map((day) => [
    day,
    { is_open: day !== "sunday", open: "08:00", close: "17:00" },
  ]),
);

const statusVariant = {
  active: "success",
  pending: "warning",
  deactivated: "secondary",
  suspended: "destructive",
  out_of_business: "secondary",
  deleted: "destructive",
};

const BASE_TABS = [
  { id: "basic", label: "Basic Info" },
  { id: "contact", label: "Contact" },
  { id: "location", label: "Location" },
  { id: "hours", label: "Hours" },
];

export default function BusinessEditor() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { pathname } = useLocation();
  const isEditMode = !!id;
  const { isAdmin } = useAuthStore();
  // Admin UI (toggle switch, grant buttons) only on /admin/ routes — not on /dashboard/ even if user is admin
  const isAdminContext = pathname.startsWith('/admin/');

  // Photos, Website, and Services tabs are only available in edit mode
  const TABS = isEditMode
    ? [
        ...BASE_TABS,
        { id: "photos", label: "Gallery" },
        { id: "website", label: "Website" },
        { id: "services", label: "Services" },
      ]
    : BASE_TABS;

  const [loading, setLoading] = useState(isEditMode);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);
  const [activeTab, setActiveTab] = useState("basic");
  const [categories, setCategories] = useState([]);
  const [regions, setRegions] = useState([]);
  const [currentBusiness, setCurrentBusiness] = useState(null);
  const [changeSummary, setChangeSummary] = useState("");
  const [subscriptions, setSubscriptions] = useState(null);
  const [subsLoading, setSubsLoading] = useState(false);
  const [subsError, setSubsError] = useState(null);
  const [grantMonths, setGrantMonths] = useState({});
  const [websiteEnabled, setWebsiteEnabled] = useState(false);
  const [togglingWebsite, setTogglingWebsite] = useState(false);
  const [hostingPeriods, setHostingPeriods] = useState(1);
  const [submittingHosting, setSubmittingHosting] = useState(false);
  const [hostingModalOpen, setHostingModalOpen] = useState(false);
  // Track whether business_tag was auto-generated (vs manually edited) in create mode
  const [tagAutoGenerated, setTagAutoGenerated] = useState(true);

  const [formData, setFormData] = useState({
    businessName: "",
    businessTag: "",
    category: "",
    region: "",
    subdomain: "",
    websiteType: "none",
    websiteUrl: "",
    tagline: "",
    description: "",
    phone: "",
    email: "",
    whatsapp: "",
    city: "",
    streetAddress: "",
    postalCode: "",
    hours: { ...defaultHours },
    siteTemplate: "classic",
    products: [],
  });

  // Slugify a string into a valid business_tag
  const slugifyTag = useCallback(
    (str) =>
      str
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "")
        .slice(0, 50),
    [],
  );

  useEffect(() => {
    loadDropdowns();
    if (isEditMode) {
      loadBusiness();
    }
  }, [id]);

  // Auto-load subscriptions when the services or website tab is opened
  useEffect(() => {
    if ((activeTab === "services" || activeTab === "website") && isEditMode && !subscriptions && !subsLoading) {
      loadSubscriptions();
    }
  }, [activeTab]);

  // Auto-populate business_tag from business name in create mode (if not manually edited)
  useEffect(() => {
    if (!isEditMode && tagAutoGenerated) {
      setFormData((prev) => ({
        ...prev,
        businessTag: slugifyTag(prev.businessName),
      }));
    }
  }, [formData.businessName, isEditMode, tagAutoGenerated, slugifyTag]);

  const loadDropdowns = async () => {
    try {
      const [catRes, regRes] = await Promise.all([
        searchAPI.getCategories(),
        searchAPI.getRegions(),
      ]);
      setCategories(catRes.data.data.categories || []);
      setRegions(regRes.data.data.regions || []);
    } catch {
      // Non-fatal — dropdowns degrade gracefully
    }
  };

  const loadBusiness = async () => {
    try {
      const res = await businessAPI.get(id);
      const business = res.data.data;
      setCurrentBusiness(business);
      const c = business.content_json || {};
      setFormData({
        businessName: business.business_name || "",
        businessTag: business.business_tag || "",
        category: business.category || "",
        region: business.region || "",
        subdomain: business.subdomain || "",
        websiteType: business.subdomain
          ? "tafuta"
          : c.contact?.website
            ? "external"
            : "none",
        websiteUrl: c.contact?.website || "",
        tagline: c.profile?.en?.tagline || "",
        description: c.profile?.en?.description || "",
        howToFind: c.profile?.en?.how_to_find || "",
        phone: c.contact?.phone || "",
        email: c.contact?.email || "",
        whatsapp: c.contact?.whatsapp || "",
        city: c.location?.city || "",
        streetAddress: c.location?.street_address || "",
        postalCode: c.location?.postal_code || "",
        hours: c.hours || { ...defaultHours },
        siteTemplate: c.site_template || "classic",
        products: Array.isArray(c.products) ? c.products : [],
      });
      setWebsiteEnabled(
        c.website_enabled === true || (c.website_enabled === undefined && !!business.has_website_hosting)
      );
    } catch {
      setError("Failed to load business. Please go back and try again.");
    } finally {
      setLoading(false);
    }
  };

  const loadSubscriptions = async () => {
    if (!isEditMode) return;
    setSubsLoading(true);
    setSubsError(null);
    try {
      if (isAdmin()) {
        const res = await adminAPI.getBusinessSubscriptions(id);
        setSubscriptions(res.data.data);
      } else {
        const [pricingRes, subsRes] = await Promise.all([
          paymentAPI.getPricing(),
          paymentAPI.getSubscriptions(id),
        ]);
        const serviceTypes = pricingRes.data.data.service_types || [];
        const subsMap = Object.fromEntries(
          (subsRes.data.data || []).map(s => [s.service_type, s])
        );
        setSubscriptions({ service_types: serviceTypes, subscriptions: subsMap });
      }
    } catch {
      setSubsError("Failed to load services.");
    } finally {
      setSubsLoading(false);
    }
  };

  const handleToggleWebsite = async (enabled) => {
    setTogglingWebsite(true);
    try {
      await adminAPI.toggleWebsite(id, enabled);
      setWebsiteEnabled(enabled);
    } catch (err) {
      setSubsError(err.response?.data?.message || "Failed to update website status.");
    } finally {
      setTogglingWebsite(false);
    }
  };

  const handlePurchaseHosting = async () => {
    setSubmittingHosting(true);
    setSubsError(null);
    try {
      const res = await paymentAPI.initiate({
        business_id: id,
        items: [{ service_type: 'website_hosting', months: hostingPeriods }],
      });
      const url = res.data?.data?.redirect_url;
      if (url) window.location.href = url;
      else setSubsError('No redirect URL returned from payment gateway.');
    } catch (err) {
      setSubsError(err.response?.data?.message || 'Failed to initiate payment.');
    } finally {
      setSubmittingHosting(false);
    }
  };

  const handleGrantSubscription = async (serviceType) => {
    const months = parseInt(grantMonths[serviceType] || "1", 10);
    try {
      await adminAPI.grantSubscription(id, { service_type: serviceType, months });
      if (serviceType === "website_hosting") setWebsiteEnabled(true);
      await loadSubscriptions();
    } catch (err) {
      setSubsError(err.response?.data?.message || "Failed to grant subscription.");
    }
  };

  const handleDeactivateSubscription = async (serviceType) => {
    try {
      await adminAPI.deactivateSubscription(id, serviceType);
      if (serviceType === "website_hosting") setWebsiteEnabled(false);
      await loadSubscriptions();
    } catch (err) {
      setSubsError(err.response?.data?.message || "Failed to deactivate subscription.");
    }
  };

  // Product/service catalog state
  const [newProduct, setNewProduct] = useState({ name: "", description: "", price: "", type: "service" });
  const [uploadingProductId, setUploadingProductId] = useState(null);

  const addProduct = () => {
    const name = newProduct.name.trim();
    if (!name) return;
    const product = { id: Date.now().toString(), name, description: newProduct.description.trim(), price: newProduct.price.trim(), type: newProduct.type || "service" };
    handleChange("products", [...formData.products, product]);
    setNewProduct({ name: "", description: "", price: "", type: "service" });
  };

  const removeProduct = (id) => {
    handleChange("products", formData.products.filter(p => p.id !== id));
  };

  const updateProduct = (id, field, value) => {
    handleChange("products", formData.products.map(p => p.id === id ? { ...p, [field]: value } : p));
  };

  const uploadProductImage = async (productId, file) => {
    const product = formData.products.find(p => p.id === productId);
    if (!product || !file) return;
    setUploadingProductId(productId);
    try {
      const fd = new FormData();
      fd.append("file", file);
      fd.append("image_type", "product");
      fd.append("image_name", product.name || productId);
      const res = await businessAPI.uploadPhoto(id, fd);
      const imageUrl = res.data?.data?.sizes?.medium || res.data?.data?.sizes?.thumb;
      if (imageUrl) {
        updateProduct(productId, "image_url", imageUrl);
      }
    } catch (err) {
      console.error("Product image upload failed", err);
    } finally {
      setUploadingProductId(null);
    }
  };

  const handleChange = (field, value) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    setError(null);
    setSuccess(false);
  };

  const handleHoursChange = (day, field, value) => {
    setFormData((prev) => ({
      ...prev,
      hours: {
        ...prev.hours,
        [day]: { ...prev.hours[day], [field]: value },
      },
    }));
  };

  const buildContentJson = () => ({
    profile: {
      en: {
        business_name: formData.businessName,
        category: formData.category,
        tagline: formData.tagline,
        description: formData.description,
        how_to_find: formData.howToFind,
      },
    },
    contact: {
      phone: formData.phone,
      email: formData.email,
      whatsapp: formData.whatsapp,
      ...(formData.websiteType === "external" && formData.websiteUrl
        ? { website: formData.websiteUrl }
        : {}),
    },
    location: {
      city: formData.city,
      street_address: formData.streetAddress,
      postal_code: formData.postalCode,
      region: formData.region,
    },
    hours: formData.hours,
    site_template: formData.siteTemplate,
    products: formData.products,
    metadata: { last_updated: new Date().toISOString() },
  });

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(null);
    setSuccess(false);

    if (!formData.businessName.trim()) {
      setError("Business name is required.");
      setActiveTab("basic");
      return;
    }
    if (!formData.category) {
      setError("Please select a category.");
      setActiveTab("basic");
      return;
    }
    if (!formData.region) {
      setError("Please select a region.");
      setActiveTab("basic");
      return;
    }

    setSaving(true);
    try {
      const content_json = buildContentJson();
      if (isEditMode) {
        await businessAPI.update(id, {
          content_json,
          change_summary: changeSummary || "Business details updated",
          business_tag: formData.businessTag || undefined,
          subdomain:
            formData.websiteType === "tafuta"
              ? formData.subdomain || undefined
              : "",
        });
        setSuccess(true);
        setChangeSummary("");
        const res = await businessAPI.get(id);
        setCurrentBusiness(res.data.data);
      } else {
        await businessAPI.create({
          business_name: formData.businessName,
          business_tag: formData.businessTag || undefined,
          category: formData.category,
          region: formData.region,
          subdomain: formData.subdomain || undefined,
          content_json,
        });
        navigate("/dashboard/businesses");
      }
    } catch (err) {
      const msg =
        err.response?.data?.message || "Failed to save. Please try again.";
      setError(msg);
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex justify-center py-12">
        <Spinner size="lg" />
      </div>
    );
  }

  const pageTitle = isEditMode
    ? currentBusiness?.business_name || "Edit Business"
    : "Add Business";

  return (
    <div className="space-y-6 max-w-2xl">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="sm" onClick={() => navigate(-1)}>
          <ArrowLeft className="h-4 w-4 mr-1" />
          Back
        </Button>
        <div className="flex-1">
          <div className="flex items-center gap-3 flex-wrap">
            <h1 className="text-2xl font-bold">{pageTitle}</h1>
            {isEditMode && currentBusiness && (
              <Badge
                variant={statusVariant[currentBusiness.status] || "secondary"}
              >
                {currentBusiness.status}
              </Badge>
            )}
          </div>
          {isEditMode && currentBusiness && (
            <p className="text-sm text-muted-foreground mt-1">
              Version {currentBusiness.content_version}
            </p>
          )}
        </div>
      </div>

      {/* Pending notice */}
      {isEditMode && currentBusiness?.status === "pending" && (
        <Alert variant="info">
          <AlertTitle>Awaiting admin approval</AlertTitle>
          <AlertDescription>
            Your business is pending review. You can still update the details
            below while waiting.
          </AlertDescription>
        </Alert>
      )}

      {error && (
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {success && (
        <Alert variant="success">
          <AlertTitle>Saved successfully</AlertTitle>
          <AlertDescription>
            Your business details have been updated.
          </AlertDescription>
        </Alert>
      )}

      <form onSubmit={handleSubmit}>
        {/* Tabs */}
        <div className="flex border-b mb-6 overflow-x-auto">
          {TABS.map((tab) => (
            <button
              key={tab.id}
              type="button"
              onClick={() => setActiveTab(tab.id)}
              className={`px-4 py-2 text-sm font-medium whitespace-nowrap border-b-2 transition-colors ${
                activeTab === tab.id
                  ? "border-primary text-primary"
                  : "border-transparent text-muted-foreground hover:text-foreground"
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Basic Info */}
        {activeTab === "basic" && (
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Building2 className="h-5 w-5" />
                Basic Information
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">
                  Business Name <span className="text-destructive">*</span>
                </label>
                <Input
                  value={formData.businessName}
                  onChange={(e) => handleChange("businessName", e.target.value)}
                  placeholder="e.g. Mama Wanjiku's Restaurant"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium mb-1">
                    Category <span className="text-destructive">*</span>
                  </label>
                  <Select
                    value={formData.category}
                    onChange={(e) => handleChange("category", e.target.value)}
                  >
                    <option value="">Select category</option>
                    {categories.map((cat) => (
                      <option key={cat} value={cat}>
                        {cat.charAt(0).toUpperCase() + cat.slice(1)}
                      </option>
                    ))}
                  </Select>
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1">
                    Region <span className="text-destructive">*</span>
                  </label>
                  <Select
                    value={formData.region}
                    onChange={(e) => handleChange("region", e.target.value)}
                  >
                    <option value="">Select region</option>
                    {regions.map((reg) => (
                      <option key={reg} value={reg}>
                        {reg}
                      </option>
                    ))}
                  </Select>
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">
                  Tagline
                </label>
                <Input
                  value={formData.tagline}
                  onChange={(e) => handleChange("tagline", e.target.value)}
                  placeholder="e.g. Best nyama choma in Machakos"
                  maxLength={120}
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">
                  Description
                </label>
                <Textarea
                  value={formData.description}
                  onChange={(e) => handleChange("description", e.target.value)}
                  placeholder="Tell people about your business..."
                  rows={4}
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">
                  How to find us
                </label>
                <Textarea
                  value={formData.howToFind}
                  onChange={(e) => handleChange("howToFind", e.target.value)}
                  placeholder="E.g. Near the big red market, enter via the side gate. Include landmarks or directions."
                  rows={3}
                  maxLength={1000}
                />
                <p className="text-xs text-muted-foreground mt-1">
                  Optional. Help customers find your shop with landmarks, gates,
                  or public transport tips.
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">
                  Business Tag
                </label>
                <Input
                  value={formData.businessTag}
                  onChange={(e) => {
                    setTagAutoGenerated(false);
                    handleChange(
                      "businessTag",
                      e.target.value
                        .toLowerCase()
                        .replace(/[^a-z0-9-]/g, "")
                        .slice(0, 64),
                    );
                  }}
                  placeholder="e.g. mama-wanjiku-restaurant"
                  maxLength={64}
                />
                <p className="text-xs text-muted-foreground mt-1">
                  Used in your media folder and image URLs. Lowercase letters,
                  numbers, and hyphens only.
                  {isEditMode && (
                    <span className="text-amber-600 ml-1">
                      Changing this tag will break existing image URLs.
                    </span>
                  )}
                </p>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Contact */}
        {activeTab === "contact" && (
          <Card>
            <CardHeader>
              <CardTitle>Contact Information</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">
                  Phone Number
                </label>
                <Input
                  type="tel"
                  value={formData.phone}
                  onChange={(e) => handleChange("phone", e.target.value)}
                  placeholder="e.g. +254 712 345 678"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Email</label>
                <Input
                  type="email"
                  value={formData.email}
                  onChange={(e) => handleChange("email", e.target.value)}
                  placeholder="e.g. info@mybusiness.com"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">
                  WhatsApp Number
                </label>
                <Input
                  type="tel"
                  value={formData.whatsapp}
                  onChange={(e) => handleChange("whatsapp", e.target.value)}
                  placeholder="e.g. +254 712 345 678"
                />
                <p className="text-xs text-muted-foreground mt-1">
                  The number customers can WhatsApp to contact you.
                </p>
              </div>

              <div className="border-t pt-4">
                <label className="block text-sm font-medium mb-3">
                  Website
                </label>
                <div className="space-y-4">
                  {/* Option 1: None */}
                  <label className="flex items-start gap-3 cursor-pointer">
                    <input
                      type="radio"
                      name="websiteType"
                      value="none"
                      checked={formData.websiteType === "none"}
                      onChange={() => handleChange("websiteType", "none")}
                      className="mt-0.5 h-4 w-4"
                    />
                    <div>
                      <div className="text-sm font-medium">No website link</div>
                      <div className="text-xs text-muted-foreground">
                        Directory listing shows contact details only
                      </div>
                    </div>
                  </label>

                  {/* Option 2: Tafuta-hosted */}
                  <label className="flex items-start gap-3 cursor-pointer">
                    <input
                      type="radio"
                      name="websiteType"
                      value="tafuta"
                      checked={formData.websiteType === "tafuta"}
                      onChange={() => handleChange("websiteType", "tafuta")}
                      className="mt-0.5 h-4 w-4"
                    />
                    <div className="flex-1">
                      <div className="text-sm font-medium">
                        Tafuta-hosted page
                        <span className="ml-2 text-xs font-normal text-amber-600">
                          Paid feature
                        </span>
                      </div>
                      <div className="text-xs text-muted-foreground mb-2">
                        We host a one-page website for you at a tafuta.ke
                        address
                      </div>
                      {formData.websiteType === "tafuta" && (
                        <div className="flex items-center gap-2">
                          <Input
                            value={formData.subdomain}
                            onChange={(e) =>
                              handleChange(
                                "subdomain",
                                e.target.value
                                  .toLowerCase()
                                  .replace(/[^a-z0-9-]/g, ""),
                              )
                            }
                            placeholder="e.g. mamawanjiku"
                            className="flex-1 h-8 text-sm"
                          />
                          <span className="text-sm text-muted-foreground whitespace-nowrap">
                            .tafuta.ke
                          </span>
                        </div>
                      )}
                    </div>
                  </label>

                  {/* Option 3: External URL */}
                  <label className="flex items-start gap-3 cursor-pointer">
                    <input
                      type="radio"
                      name="websiteType"
                      value="external"
                      checked={formData.websiteType === "external"}
                      onChange={() => handleChange("websiteType", "external")}
                      className="mt-0.5 h-4 w-4"
                    />
                    <div className="flex-1">
                      <div className="text-sm font-medium">
                        External website
                      </div>
                      <div className="text-xs text-muted-foreground mb-2">
                        Link to your own website
                      </div>
                      {formData.websiteType === "external" && (
                        <Input
                          type="url"
                          value={formData.websiteUrl}
                          onChange={(e) =>
                            handleChange("websiteUrl", e.target.value)
                          }
                          placeholder="https://www.mywebsite.com"
                          className="h-8 text-sm"
                        />
                      )}
                    </div>
                  </label>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Location */}
        {activeTab === "location" && (
          <Card>
            <CardHeader>
              <CardTitle>Location</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">
                  Street Address
                </label>
                <Input
                  value={formData.streetAddress}
                  onChange={(e) =>
                    handleChange("streetAddress", e.target.value)
                  }
                  placeholder="e.g. 12 Market Street"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">
                  Town / City
                </label>
                <Input
                  value={formData.city}
                  onChange={(e) => handleChange("city", e.target.value)}
                  placeholder="e.g. Machakos Town"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">
                  Postal Code
                </label>
                <Input
                  value={formData.postalCode}
                  onChange={(e) => handleChange("postalCode", e.target.value)}
                  placeholder="e.g. 90100"
                />
                <p className="text-xs text-muted-foreground mt-1">
                  Kenya post office postal code (not a zip code).
                </p>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Hours */}
        {activeTab === "hours" && (
          <Card>
            <CardHeader>
              <CardTitle>Business Hours</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {DAYS.map((day) => (
                <div key={day} className="flex items-center gap-3 flex-wrap">
                  <div className="w-24 text-sm font-medium">
                    {DAY_LABELS[day]}
                  </div>
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={formData.hours[day]?.is_open ?? true}
                      onChange={(e) =>
                        handleHoursChange(day, "is_open", e.target.checked)
                      }
                      className="h-4 w-4"
                    />
                    <span className="text-sm text-muted-foreground">Open</span>
                  </label>
                  {formData.hours[day]?.is_open ? (
                    <>
                      <Input
                        type="time"
                        value={formData.hours[day]?.open || "08:00"}
                        onChange={(e) =>
                          handleHoursChange(day, "open", e.target.value)
                        }
                        className="w-32 h-8 text-sm"
                      />
                      <span className="text-sm text-muted-foreground">to</span>
                      <Input
                        type="time"
                        value={formData.hours[day]?.close || "17:00"}
                        onChange={(e) =>
                          handleHoursChange(day, "close", e.target.value)
                        }
                        className="w-32 h-8 text-sm"
                      />
                    </>
                  ) : (
                    <span className="text-sm text-muted-foreground">
                      Closed
                    </span>
                  )}
                </div>
              ))}
            </CardContent>
          </Card>
        )}

        {/* Photos */}
        {activeTab === "photos" && isEditMode && (
          <Card>
            <CardHeader>
              <CardTitle>Photos</CardTitle>
            </CardHeader>
            <CardContent>
              <ImageManager
                businessId={id}
                businessTag={formData.businessTag}
                canDelete={
                  isAdmin() ||
                  ["owner", "admin"].includes(currentBusiness?.user_role)
                }
              />
            </CardContent>
          </Card>
        )}

        {/* Website */}
        {activeTab === "website" && isEditMode && (
          <>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Globe className="h-5 w-5" />
                One-Page Website
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-sm text-muted-foreground">
                Choose a template for your business's public website at{" "}
                <span className="font-medium text-foreground">
                  /site/{formData.businessTag}
                </span>
                . The page is built from your business info, logo, and photos.
              </p>

              <div className="grid gap-4 sm:grid-cols-3">
                {[
                  {
                    id: "classic",
                    label: "Classic",
                    icon: Monitor,
                    description: "Professional two-column layout with header, contact panel, and description.",
                  },
                  {
                    id: "bold",
                    label: "Bold",
                    icon: Zap,
                    description: "Dark hero header with large type and vibrant accent. Eye-catching.",
                  },
                  {
                    id: "minimal",
                    label: "Minimal",
                    icon: Minus,
                    description: "Clean single-column layout. Text-forward, loads fast.",
                  },
                ].map((tpl) => {
                  const Icon = tpl.icon;
                  const selected = formData.siteTemplate === tpl.id;
                  return (
                    <div key={tpl.id} className="flex flex-col gap-1.5">
                      <button
                        type="button"
                        onClick={() => handleChange("siteTemplate", tpl.id)}
                        className={`rounded-lg border-2 p-4 text-left transition-all ${
                          selected
                            ? "border-primary bg-primary/5"
                            : "border-border hover:border-muted-foreground"
                        }`}
                      >
                        <div className="flex items-center gap-2 mb-2">
                          <Icon className={`h-5 w-5 ${selected ? "text-primary" : "text-muted-foreground"}`} />
                          <span className={`text-sm font-semibold ${selected ? "text-primary" : ""}`}>
                            {tpl.label}
                          </span>
                          {selected && (
                            <span className="ml-auto text-xs bg-primary text-primary-foreground rounded-full px-2 py-0.5">
                              Active
                            </span>
                          )}
                        </div>
                        <p className="text-xs text-muted-foreground leading-relaxed">{tpl.description}</p>
                      </button>
                      {formData.businessTag && (
                        <a
                          href={`/site/${formData.businessTag}?template=${tpl.id}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-xs text-center text-primary underline hover:no-underline"
                        >
                          Preview {tpl.label}
                        </a>
                      )}
                    </div>
                  );
                })}
              </div>

              <p className="text-xs text-muted-foreground">
                Save changes below to apply the selected template.
              </p>

              {/* Website live status / purchase */}
              {isAdminContext ? (
                <div className={`flex items-center justify-between rounded-lg px-4 py-3 border ${websiteEnabled ? "bg-green-50 border-green-200" : "bg-gray-50 border-gray-200"}`}>
                  <div>
                    <p className="text-sm font-semibold">
                      {websiteEnabled ? "Website is Live" : "Website is Off"}
                    </p>
                    {websiteEnabled && formData.businessTag ? (
                      <a
                        href={`/site/${formData.businessTag}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-blue-600 hover:underline"
                      >
                        tafuta.ke/site/{formData.businessTag}
                      </a>
                    ) : !websiteEnabled && (
                      <p className="text-xs text-muted-foreground">Website is not accessible to visitors</p>
                    )}
                  </div>
                  <button
                    type="button"
                    disabled={togglingWebsite}
                    onClick={() => handleToggleWebsite(!websiteEnabled)}
                    className={`relative inline-flex h-6 w-11 shrink-0 rounded-full border-2 border-transparent transition-colors duration-200 focus:outline-none disabled:opacity-50 ${websiteEnabled ? "bg-green-500" : "bg-gray-300"}`}
                  >
                    <span
                      className={`pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${websiteEnabled ? "translate-x-5" : "translate-x-0"}`}
                    />
                  </button>
                </div>
              ) : websiteEnabled ? (
                <div className="flex items-center gap-3 rounded-lg px-4 py-3 border bg-green-50 border-green-200">
                  <div className="h-2 w-2 rounded-full bg-green-500 shrink-0" />
                  <div className="flex-1">
                    <p className="text-sm font-semibold text-green-800">Website is Live</p>
                    {formData.businessTag && (
                      <a
                        href={`/site/${formData.businessTag}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-blue-600 hover:underline"
                      >
                        tafuta.ke/site/{formData.businessTag}
                      </a>
                    )}
                  </div>
                </div>
              ) : (
                <div className="flex items-center justify-between rounded-lg px-4 py-3 border bg-gray-50 border-gray-200">
                  <div>
                    <p className="text-sm font-semibold">Website is Off</p>
                    <p className="text-xs text-muted-foreground">Activate hosting to make your website public</p>
                  </div>
                  <Button
                    type="button"
                    size="sm"
                    onClick={() => setHostingModalOpen(true)}
                  >
                    Activate Website
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Products / Services catalog */}
          <Card className="mt-4">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-base">
                <Package className="h-5 w-5" />
                Products &amp; Services
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-sm text-muted-foreground">
                List products or services you offer. These appear on your public website.
              </p>

              {/* Existing products */}
              {formData.products.length > 0 && (
                <div className="space-y-3">
                  {formData.products.map((product) => (
                    <div key={product.id} className="rounded-lg border p-3 space-y-2">
                      <div className="flex items-start gap-3">
                        {/* Image thumbnail / upload trigger */}
                        <label className="relative shrink-0 cursor-pointer group">
                          <input
                            type="file"
                            accept="image/*"
                            className="sr-only"
                            onChange={(e) => e.target.files?.[0] && uploadProductImage(product.id, e.target.files[0])}
                          />
                          <div className="h-14 w-14 rounded-lg overflow-hidden border bg-muted flex items-center justify-center">
                            {uploadingProductId === product.id ? (
                              <Spinner size="sm" />
                            ) : product.image_url ? (
                              <img src={product.image_url} alt={product.name} className="h-full w-full object-cover" />
                            ) : (
                              <ImageOff className="h-5 w-5 text-muted-foreground" />
                            )}
                          </div>
                          <div className="absolute inset-0 rounded-lg bg-black/40 opacity-0 group-hover:opacity-100 flex items-center justify-center transition-opacity">
                            <Camera className="h-4 w-4 text-white" />
                          </div>
                        </label>

                        <div className="flex-1 space-y-2 min-w-0">
                          <div className="flex items-center gap-2">
                            <Input
                              value={product.name}
                              onChange={(e) => updateProduct(product.id, "name", e.target.value)}
                              placeholder="Name"
                              className="flex-1 text-sm"
                            />
                            <span className="text-xs text-muted-foreground shrink-0">KES</span>
                            <Input
                              value={product.price}
                              onChange={(e) => updateProduct(product.id, "price", e.target.value)}
                              placeholder="Price"
                              className="w-24 text-sm"
                            />
                            <Button
                              type="button"
                              variant="ghost"
                              size="sm"
                              className="text-destructive hover:bg-destructive/10 shrink-0"
                              onClick={() => removeProduct(product.id)}
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </div>
                          <div className="flex items-center gap-2">
                            <Input
                              value={product.description}
                              onChange={(e) => updateProduct(product.id, "description", e.target.value)}
                              placeholder="Short description (optional)"
                              className="flex-1 text-sm"
                            />
                            <div className="flex shrink-0 rounded-md border overflow-hidden text-xs font-medium">
                              <button
                                type="button"
                                onClick={() => updateProduct(product.id, "type", "service")}
                                className={`px-2.5 py-1.5 transition-colors ${(product.type || "service") === "service" ? "bg-primary text-primary-foreground" : "bg-background text-muted-foreground hover:bg-muted"}`}
                              >
                                Service
                              </button>
                              <button
                                type="button"
                                onClick={() => updateProduct(product.id, "type", "product")}
                                className={`px-2.5 py-1.5 transition-colors ${product.type === "product" ? "bg-primary text-primary-foreground" : "bg-background text-muted-foreground hover:bg-muted"}`}
                              >
                                Product
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {/* Add new product */}
              <div className="rounded-lg border border-dashed p-3 space-y-2">
                <p className="text-xs font-medium text-muted-foreground">Add a product or service</p>
                <div className="flex items-center gap-2">
                  <Input
                    value={newProduct.name}
                    onChange={(e) => setNewProduct(p => ({ ...p, name: e.target.value }))}
                    placeholder="Name *"
                    className="flex-1 text-sm"
                    onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), addProduct())}
                  />
                  <span className="text-xs text-muted-foreground shrink-0">KES</span>
                  <Input
                    value={newProduct.price}
                    onChange={(e) => setNewProduct(p => ({ ...p, price: e.target.value }))}
                    placeholder="Price"
                    className="w-24 text-sm"
                    onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), addProduct())}
                  />
                </div>
                <div className="flex gap-2">
                  <Input
                    value={newProduct.description}
                    onChange={(e) => setNewProduct(p => ({ ...p, description: e.target.value }))}
                    placeholder="Description (optional)"
                    className="flex-1 text-sm"
                    onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), addProduct())}
                  />
                  <div className="flex shrink-0 rounded-md border overflow-hidden text-xs font-medium">
                    <button
                      type="button"
                      onClick={() => setNewProduct(p => ({ ...p, type: "service" }))}
                      className={`px-2.5 py-1.5 transition-colors ${newProduct.type !== "product" ? "bg-primary text-primary-foreground" : "bg-background text-muted-foreground hover:bg-muted"}`}
                    >
                      Service
                    </button>
                    <button
                      type="button"
                      onClick={() => setNewProduct(p => ({ ...p, type: "product" }))}
                      className={`px-2.5 py-1.5 transition-colors ${newProduct.type === "product" ? "bg-primary text-primary-foreground" : "bg-background text-muted-foreground hover:bg-muted"}`}
                    >
                      Product
                    </button>
                  </div>
                  <Button type="button" size="sm" onClick={addProduct} disabled={!newProduct.name.trim()}>
                    <Plus className="h-4 w-4 mr-1" /> Add
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
          </>
        )}

        {/* Services */}
        {activeTab === "services" && isEditMode && (
          <Card>
            <CardHeader>
              <CardTitle>Paid Services</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {subsError && (
                <Alert variant="destructive">
                  <AlertDescription>{subsError}</AlertDescription>
                </Alert>
              )}
              {subsLoading && <Spinner size="sm" />}
              {subscriptions && (
                <div className="divide-y">
                  {subscriptions.service_types.map((stDef) => {
                    const type = stDef.id ?? stDef;
                    const label = stDef.label ?? type.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
                    const billingType = stDef.billing_type || 'monthly';
                    const isOneTime = billingType === 'one_time';
                    const billingLabel = billingType === 'weekly' ? 'weekly' : billingType === 'annual' ? 'annual' : billingType === 'one_time' ? 'one-time' : 'monthly';
                    const stPrice = Number(stDef.price ?? stDef.price_per_month ?? 0);
                    const sub = subscriptions.subscriptions[type];
                    const isActive = sub?.status === "active" &&
                      (!sub.expiration_date || new Date(sub.expiration_date) > new Date());
                    return (
                      <div key={type} className="flex items-center gap-3 py-3 flex-wrap">
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className="text-sm font-medium">{label}</span>
                            <span className="text-xs text-muted-foreground">
                              {billingLabel}{!isOneTime && stPrice > 0 ? ` · KES ${stPrice.toLocaleString()}` : ''}
                            </span>
                            {isActive ? (
                              <Badge variant="success">Active</Badge>
                            ) : sub ? (
                              <Badge variant="secondary">Inactive</Badge>
                            ) : (
                              <Badge variant="outline">{isAdminContext ? "Not granted" : "Not purchased"}</Badge>
                            )}
                          </div>
                          {stDef.description && (
                            <p className="text-xs text-muted-foreground mt-0.5">{stDef.description}</p>
                          )}
                          {!isOneTime && sub?.expiration_date && (
                            <p className="text-xs text-muted-foreground mt-0.5">
                              Expires: {new Date(sub.expiration_date).toLocaleDateString()}
                            </p>
                          )}
                        </div>
                        {isAdminContext && (
                          <div className="flex items-center gap-2">
                            {!isOneTime && (
                              <>
                                <Input
                                  type="number"
                                  min="1"
                                  max="60"
                                  value={grantMonths[type] || "1"}
                                  onChange={(e) => setGrantMonths(prev => ({ ...prev, [type]: e.target.value }))}
                                  className="w-16 h-8 text-sm text-center"
                                />
                                <span className="text-xs text-muted-foreground">mo</span>
                              </>
                            )}
                            <Button
                              type="button"
                              size="sm"
                              onClick={() => handleGrantSubscription(type)}
                            >
                              {isActive ? (isOneTime ? "Re-grant" : "Extend") : "Grant"}
                            </Button>
                            {isActive && (
                              <Button
                                type="button"
                                size="sm"
                                variant="destructive"
                                onClick={() => handleDeactivateSubscription(type)}
                              >
                                Revoke
                              </Button>
                            )}
                          </div>
                        )}
                        {!isAdminContext && !isActive && (
                          <Button
                            type="button"
                            size="sm"
                            variant="outline"
                            onClick={() => navigate(`/checkout/${id}`)}
                          >
                            Purchase
                          </Button>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {/* Change notes and save — hidden on Photos and Services tabs */}
        {activeTab !== "photos" && activeTab !== "services" && (
          <>
            {isEditMode && (
              <div className="mt-4">
                <label className="block text-sm font-medium mb-1">
                  Change Notes (optional)
                </label>
                <Input
                  value={changeSummary}
                  onChange={(e) => setChangeSummary(e.target.value)}
                  placeholder="e.g. Updated opening hours for the holiday season"
                />
              </div>
            )}

            <div className="mt-6 flex gap-3">
              <Button type="submit" disabled={saving}>
                {saving ? (
                  <>
                    <Spinner size="sm" className="mr-2" />
                    Saving...
                  </>
                ) : (
                  <>
                    <Save className="h-4 w-4 mr-2" />
                    {isEditMode ? "Save Changes" : "Submit Business"}
                  </>
                )}
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => navigate(-1)}
              >
                Cancel
              </Button>
            </div>
          </>
        )}
      </form>

      {/* Website hosting payment modal — rendered at root so fixed positioning works cleanly */}
      {hostingModalOpen && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4"
          onClick={() => { if (!submittingHosting) setHostingModalOpen(false); }}
        >
          <div className="absolute inset-0 bg-black/50" />
          <div
            className="relative z-10 w-full max-w-md rounded-xl bg-white dark:bg-gray-900 shadow-2xl"
            onClick={e => e.stopPropagation()}
          >
            {/* Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b">
              <div className="flex items-center gap-2">
                <CreditCard className="h-5 w-5 text-primary" />
                <h2 className="text-base font-semibold">Activate Website Hosting</h2>
              </div>
              <button
                type="button"
                disabled={submittingHosting}
                onClick={() => setHostingModalOpen(false)}
                className="text-muted-foreground hover:text-foreground disabled:opacity-40"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            {/* Body */}
            <div className="px-6 py-5 space-y-5">
              {subsLoading && !subscriptions && (
                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Spinner size="sm" />Loading pricing…
                </div>
              )}
              {!subsLoading && !subscriptions?.service_types?.find(s => s.id === 'website_hosting') && (
                <p className="text-sm text-destructive">Website hosting pricing is not configured. Please contact support.</p>
              )}
              {subscriptions?.service_types?.find(s => s.id === 'website_hosting') && (() => {
                const wsDef = subscriptions.service_types.find(s => s.id === 'website_hosting');
                const wsPrice = Number(wsDef.price ?? wsDef.price_per_month ?? 0);
                const wsBt = wsDef.billing_type || 'monthly';
                const wsIsOneTime = wsBt === 'one_time';
                const wsUnit = wsBt === 'weekly' ? 'week' : wsBt === 'annual' ? 'year' : 'month';
                const wsTotal = wsIsOneTime ? wsPrice : wsPrice * hostingPeriods;
                const wsVat = wsTotal * 0.16;
                const wsTotalVat = wsTotal + wsVat;
                return (
                  <>
                    <div className="rounded-lg border bg-muted/40 p-4 space-y-1">
                      <p className="text-sm font-medium">{wsDef.label || 'Website Hosting'}</p>
                      {wsDef.description && <p className="text-xs text-muted-foreground">{wsDef.description}</p>}
                      <p className="text-sm font-semibold text-primary mt-1">
                        KES {wsPrice.toLocaleString()} / {wsUnit}
                      </p>
                    </div>

                    {!wsIsOneTime && (
                      <div className="space-y-2">
                        <label className="text-sm font-medium">How many {wsUnit}s?</label>
                        <div className="flex items-center gap-2">
                          <button type="button" className="w-9 h-9 rounded-lg border text-lg font-bold hover:bg-accent" onClick={() => setHostingPeriods(p => Math.max(1, p - 1))}>−</button>
                          <input
                            type="number"
                            min={1}
                            max={52}
                            value={hostingPeriods}
                            onChange={e => setHostingPeriods(Math.max(1, Math.min(52, parseInt(e.target.value) || 1)))}
                            className="w-16 text-center border rounded-lg px-2 py-2 text-sm font-medium"
                          />
                          <button type="button" className="w-9 h-9 rounded-lg border text-lg font-bold hover:bg-accent" onClick={() => setHostingPeriods(p => Math.min(52, p + 1))}>+</button>
                          <span className="text-sm text-muted-foreground ml-1">{wsUnit}{hostingPeriods > 1 ? 's' : ''}</span>
                        </div>
                      </div>
                    )}

                    <div className="rounded-lg border divide-y text-sm">
                      {!wsIsOneTime && (
                        <div className="flex justify-between px-4 py-2">
                          <span className="text-muted-foreground">{hostingPeriods} {wsUnit}{hostingPeriods > 1 ? 's' : ''} × KES {wsPrice.toLocaleString()}</span>
                          <span>KES {wsTotal.toLocaleString()}</span>
                        </div>
                      )}
                      <div className="flex justify-between px-4 py-2">
                        <span className="text-muted-foreground">VAT (16%)</span>
                        <span>KES {wsVat.toLocaleString('en-KE', { maximumFractionDigits: 0 })}</span>
                      </div>
                      <div className="flex justify-between px-4 py-2 font-semibold">
                        <span>Total</span>
                        <span>KES {wsTotalVat.toLocaleString('en-KE', { maximumFractionDigits: 0 })}</span>
                      </div>
                    </div>

                    {subsError && <p className="text-sm text-destructive">{subsError}</p>}

                    <p className="text-xs text-muted-foreground">
                      You'll be redirected to PesaPal to complete payment via M-Pesa, Airtel Money, or card. Your website activates automatically once payment is confirmed.
                    </p>
                  </>
                );
              })()}
            </div>

            {/* Footer */}
            {subscriptions?.service_types?.find(s => s.id === 'website_hosting') && (
              <div className="flex gap-3 px-6 py-4 border-t">
                <Button type="button" variant="outline" className="flex-1" disabled={submittingHosting} onClick={() => setHostingModalOpen(false)}>
                  Cancel
                </Button>
                <Button type="button" className="flex-1" disabled={submittingHosting} onClick={handlePurchaseHosting}>
                  {submittingHosting ? <><Spinner size="sm" className="mr-2" />Redirecting…</> : 'Pay & Activate'}
                </Button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
