-- Migration: Create invoices table
-- Created: 2026-08-23

CREATE SEQUENCE IF NOT EXISTS invoice_number_seq START 1;

CREATE TABLE IF NOT EXISTS invoices (
  invoice_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_number VARCHAR(30) UNIQUE,
  business_id    UUID NOT NULL REFERENCES businesses(business_id) ON DELETE CASCADE,
  created_by     UUID REFERENCES users(user_id),
  status         VARCHAR(20) DEFAULT 'draft'
                   CHECK (status IN ('draft', 'sent', 'paid', 'overdue', 'cancelled')),
  issue_date     DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date       DATE,
  items          JSONB NOT NULL DEFAULT '[]',
  subtotal       DECIMAL(10,2) NOT NULL DEFAULT 0,
  vat_amount     DECIMAL(10,2) NOT NULL DEFAULT 0,
  total_amount   DECIMAL(10,2) NOT NULL DEFAULT 0,
  notes          TEXT,
  paid_at        TIMESTAMP,
  transaction_id UUID REFERENCES transactions(transaction_id),
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_invoices_business_id  ON invoices(business_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status       ON invoices(status);
CREATE INDEX IF NOT EXISTS idx_invoices_issue_date   ON invoices(issue_date);

COMMENT ON TABLE invoices IS 'Business service invoices generated by admin';
COMMENT ON COLUMN invoices.items IS 'JSON array: [{service_type, label, description, months, unit_price, total}]';
